services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cafedb
      MYSQL_USER: cafeuser
      MYSQL_PASSWORD: cafepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aspnetcoreapp-network


  backend:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: Backend # Ensure this path is correct
      dockerfile: Dockerfile
    networks:
      - aspnetcoreapp-network
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=cafedb;User=root;Password=rootpassword;"
     
volumes:
  mysql-data:

networks:
  aspnetcoreapp-network:
    driver: bridge
